"""refactor_escalas_structure

Revision ID: 0693a4ad2c0b
Revises: 24639bfc489f
Create Date: 2025-07-31 18:47:18.550900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0693a4ad2c0b'
down_revision = '24639bfc489f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Criar tabela escala_usuarios com estrutura completa
    op.create_table('escala_usuarios',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('escala_id', sa.Integer(), nullable=False),
        sa.Column('usuario_id', sa.Integer(), nullable=False),
        sa.Column('setor', sa.String(length=100), nullable=False),
        sa.Column('status', sa.String(length=50), nullable=False, server_default='Pendente'),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['escala_id'], ['escalas.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    
    # 2. Criar índices para performance
    op.create_index(op.f('ix_escala_usuarios_escala_id'), 'escala_usuarios', ['escala_id'], unique=False)
    op.create_index(op.f('ix_escala_usuarios_usuario_id'), 'escala_usuarios', ['usuario_id'], unique=False)
    
    # 3. Migrar dados existentes da tabela escalas para escala_usuarios
    op.execute("""
        INSERT INTO escala_usuarios (escala_id, usuario_id, setor, status, created_at, updated_at)
        SELECT 
            id as escala_id,
            usuario_id,
            COALESCE(setor, 'Geral') as setor,
            'Pendente' as status,
            created_at,
            updated_at
        FROM escalas 
        WHERE usuario_id IS NOT NULL
    """)
    
    # 4. Remover foreign key constraint da tabela escalas
    op.drop_constraint('escalas_usuario_id_fkey', 'escalas', type_='foreignkey')
    
    # 5. Remover colunas da tabela escalas
    op.drop_column('escalas', 'usuario_id')
    op.drop_column('escalas', 'setor')
    
    # 6. Remover índices relacionados
    op.drop_index(op.f('ix_escalas_usuario_id'), table_name='escalas')
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Restaurar colunas na tabela escalas
    op.add_column('escalas', sa.Column('usuario_id', sa.Integer(), nullable=True))
    op.add_column('escalas', sa.Column('setor', sa.String(length=100), nullable=True))
    
    # 2. Restaurar dados da tabela escala_usuarios
    op.execute("""
        UPDATE escalas 
        SET usuario_id = eu.usuario_id, setor = eu.setor
        FROM escala_usuarios eu
        WHERE escalas.id = eu.escala_id
    """)
    
    # 3. Adicionar foreign key constraint
    op.create_foreign_key('escalas_usuario_id_fkey', 'escalas', 'usuarios', ['usuario_id'], ['id'], ondelete='CASCADE')
    
    # 4. Criar índice para usuario_id
    op.create_index(op.f('ix_escalas_usuario_id'), 'escalas', ['usuario_id'], unique=False)
    
    # 5. Remover índices da tabela escala_usuarios
    op.drop_index(op.f('ix_escala_usuarios_usuario_id'), table_name='escala_usuarios')
    op.drop_index(op.f('ix_escala_usuarios_escala_id'), table_name='escala_usuarios')
    
    # 6. Remover tabela escala_usuarios
    op.drop_table('escala_usuarios')
    
    # ### end Alembic commands ### 