"""refactor_escalas_structure

Revision ID: 19cd0b3623a9
Revises: 0693a4ad2c0b
Create Date: 2025-07-31 18:48:05.130112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19cd0b3623a9'
down_revision = '0693a4ad2c0b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Adicionar colunas que faltam na tabela escala_usuarios
    op.add_column('escala_usuarios', sa.Column('status', sa.String(length=50), nullable=False, server_default='Pendente'))
    op.add_column('escala_usuarios', sa.Column('updated_at', sa.DateTime(), nullable=True))
    
    # 2. Migrar dados existentes da tabela escalas para escala_usuarios
    op.execute("""
        INSERT INTO escala_usuarios (escala_id, usuario_id, setor, status, created_at, updated_at)
        SELECT 
            id as escala_id,
            usuario_id,
            COALESCE(setor, 'Geral') as setor,
            'Pendente' as status,
            created_at,
            updated_at
        FROM escalas 
        WHERE usuario_id IS NOT NULL
        AND id NOT IN (SELECT escala_id FROM escala_usuarios)
    """)
    
    # 3. Remover foreign key constraint da tabela escalas
    op.drop_constraint('escalas_usuario_id_fkey', 'escalas', type_='foreignkey')
    
    # 4. Remover colunas da tabela escalas
    op.drop_column('escalas', 'usuario_id')
    op.drop_column('escalas', 'setor')
    
    # 5. Remover índices relacionados
    op.drop_index(op.f('ix_escalas_usuario_id'), table_name='escalas')
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Restaurar colunas na tabela escalas
    op.add_column('escalas', sa.Column('usuario_id', sa.Integer(), nullable=True))
    op.add_column('escalas', sa.Column('setor', sa.String(length=100), nullable=True))
    
    # 2. Restaurar dados da tabela escala_usuarios
    op.execute("""
        UPDATE escalas 
        SET usuario_id = eu.usuario_id, setor = eu.setor
        FROM escala_usuarios eu
        WHERE escalas.id = eu.escala_id
    """)
    
    # 3. Adicionar foreign key constraint
    op.create_foreign_key('escalas_usuario_id_fkey', 'escalas', 'usuarios', ['usuario_id'], ['id'], ondelete='CASCADE')
    
    # 4. Criar índice para usuario_id
    op.create_index(op.f('ix_escalas_usuario_id'), 'escalas', ['usuario_id'], unique=False)
    
    # 5. Remover coluna status da tabela escala_usuarios
    op.drop_column('escala_usuarios', 'status')
    
    # ### end Alembic commands ### 