"""initial_migration_clean

Revision ID: 24639bfc489f
Revises: 
Create Date: 2025-07-24 16:49:21.800238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24639bfc489f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estabelecimentos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('endereco', sa.Text(), nullable=False),
    sa.Column('latitude', sa.DECIMAL(precision=10, scale=8), nullable=False),
    sa.Column('longitude', sa.DECIMAL(precision=11, scale=8), nullable=False),
    sa.Column('raio_checkin', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('cpf', sa.String(length=14), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=True),
    sa.Column('token', sa.String(length=255), nullable=True),
    sa.Column('perfil', sa.Enum('ADMINISTRADOR', 'SUPERVISOR', 'SOCIO', name='perfilenum'), nullable=False),
    sa.Column('documentos', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('ATIVO', 'INATIVO', name='statususuarioenum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_cpf'), 'usuarios', ['cpf'], unique=True)
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_table('documentos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('nome_arquivo', sa.String(length=255), nullable=False),
    sa.Column('tipo_documento', sa.String(length=100), nullable=False),
    sa.Column('arquivo_path', sa.String(length=500), nullable=False),
    sa.Column('tamanho_bytes', sa.Integer(), nullable=False),
    sa.Column('mimetype', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documentos_usuario_id'), 'documentos', ['usuario_id'], unique=False)
    op.create_table('escalas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('hora_fim', sa.Time(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('estabelecimento_id', sa.Integer(), nullable=False),
    sa.Column('setor', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('PENDENTE', 'CONFIRMADO', 'AUSENTE', name='statusescalaenum'), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['estabelecimento_id'], ['estabelecimentos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_escalas_data_fim'), 'escalas', ['data_fim'], unique=False)
    op.create_index(op.f('ix_escalas_data_inicio'), 'escalas', ['data_inicio'], unique=False)
    op.create_index(op.f('ix_escalas_estabelecimento_id'), 'escalas', ['estabelecimento_id'], unique=False)
    op.create_index(op.f('ix_escalas_usuario_id'), 'escalas', ['usuario_id'], unique=False)
    op.create_table('estabelecimento_profissionais',
    sa.Column('estabelecimento_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['estabelecimento_id'], ['estabelecimentos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('estabelecimento_id', 'usuario_id')
    )
    op.create_table('logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('acao', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('dados_extras', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_logs_acao'), 'logs', ['acao'], unique=False)
    op.create_index(op.f('ix_logs_created_at'), 'logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_logs_usuario_id'), 'logs', ['usuario_id'], unique=False)
    op.create_table('checkins',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('escala_id', sa.Integer(), nullable=False),
    sa.Column('data_hora', sa.DateTime(), nullable=False),
    sa.Column('gps_lat', sa.DECIMAL(precision=10, scale=8), nullable=False),
    sa.Column('gps_long', sa.DECIMAL(precision=11, scale=8), nullable=False),
    sa.Column('status', sa.Enum('REALIZADO', 'AUSENTE', 'FORA_DE_LOCAL', name='statuscheckinenum'), nullable=False),
    sa.Column('endereco', sa.String(length=500), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['escala_id'], ['escalas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_checkins_data_hora'), 'checkins', ['data_hora'], unique=False)
    op.create_index(op.f('ix_checkins_escala_id'), 'checkins', ['escala_id'], unique=False)
    op.create_index(op.f('ix_checkins_usuario_id'), 'checkins', ['usuario_id'], unique=False)
    op.create_table('escala_supervisores',
    sa.Column('escala_id', sa.Integer(), nullable=False),
    sa.Column('supervisor_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['escala_id'], ['escalas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supervisor_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('escala_id', 'supervisor_id')
    )
    op.create_table('transferencias_plantao',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('escala_original_id', sa.Integer(), nullable=False),
    sa.Column('usuario_origem_id', sa.Integer(), nullable=False),
    sa.Column('usuario_destino_id', sa.Integer(), nullable=False),
    sa.Column('motivo', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('aprovado_por_id', sa.Integer(), nullable=True),
    sa.Column('data_aprovacao', sa.DateTime(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['aprovado_por_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['escala_original_id'], ['escalas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_destino_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_origem_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transferencias_plantao_escala_original_id'), 'transferencias_plantao', ['escala_original_id'], unique=False)
    op.create_index(op.f('ix_transferencias_plantao_usuario_destino_id'), 'transferencias_plantao', ['usuario_destino_id'], unique=False)
    op.create_index(op.f('ix_transferencias_plantao_usuario_origem_id'), 'transferencias_plantao', ['usuario_origem_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transferencias_plantao_usuario_origem_id'), table_name='transferencias_plantao')
    op.drop_index(op.f('ix_transferencias_plantao_usuario_destino_id'), table_name='transferencias_plantao')
    op.drop_index(op.f('ix_transferencias_plantao_escala_original_id'), table_name='transferencias_plantao')
    op.drop_table('transferencias_plantao')
    op.drop_table('escala_supervisores')
    op.drop_index(op.f('ix_checkins_usuario_id'), table_name='checkins')
    op.drop_index(op.f('ix_checkins_escala_id'), table_name='checkins')
    op.drop_index(op.f('ix_checkins_data_hora'), table_name='checkins')
    op.drop_table('checkins')
    op.drop_index(op.f('ix_logs_usuario_id'), table_name='logs')
    op.drop_index(op.f('ix_logs_created_at'), table_name='logs')
    op.drop_index(op.f('ix_logs_acao'), table_name='logs')
    op.drop_table('logs')
    op.drop_table('estabelecimento_profissionais')
    op.drop_index(op.f('ix_escalas_usuario_id'), table_name='escalas')
    op.drop_index(op.f('ix_escalas_estabelecimento_id'), table_name='escalas')
    op.drop_index(op.f('ix_escalas_data_inicio'), table_name='escalas')
    op.drop_index(op.f('ix_escalas_data_fim'), table_name='escalas')
    op.drop_table('escalas')
    op.drop_index(op.f('ix_documentos_usuario_id'), table_name='documentos')
    op.drop_table('documentos')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_cpf'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_table('estabelecimentos')
    # ### end Alembic commands ### 